CREATE TABLE EVENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CASE_DETAIL_ID TEXT NOT NULL,
    EVENT_NUMBER INTEGER NOT NULL,
    DATE TEXT NOT NULL,
    TIME TEXT,
    OFFICER TEXT,
    RESULT TEXT,
    TYPE TEXT NOT NULL,
    FOREIGN KEY(CASE_DETAIL_ID) REFERENCES CASE_DETAIL(ID),
    UNIQUE(CASE_DETAIL_ID, EVENT_NUMBER)
);
