CREATE TABLE SETTING (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CASE_NUMBER TEXT NOT NULL,
    CASE_LINK TEXT,
    SETTING_TYPE TEXT ,
    SETTING_STYLE TEXT ,
    JUDICIAL_OFFICER TEXT ,
    SETTING_DATE TEXT ,
    SETTING_TIME TEXT ,
    HEARING_TYPE TEXT 
);
CREATE UNIQUE INDEX idx_setting_case_style_date_time
ON SETTING (CASE_NUMBER,SETTING_STYLE,SETTING_DATE,SETTING_TIME);