CREATE TABLE DISPOSITION (
    ID SERIAL PRIMARY KEY,
    CASE_NUMBER TEXT NOT NULL UNIQUE,
    TYPE TEXT,
    DATE TEXT NOT NULL,
    AMOUNT TEXT,
    AWARDED_TO TEXT,
    AWARDED_AGAINST TEXT,
    ATTORNEYS_FOR_PLAINTIFFS TEXT,
    ATTORNEYS_FOR_DEFENDANTS TEXT,
    JUDGEMENT_FOR TEXT,
    COMMENTS TEXT
    FOREIGN KEY(CASE_NUMBER) REFERENCES CASE_DETAIL(CASE_NUMBER)
);
