CREATE TABLE EVENT (
    ID SERIAL PRIMARY KEY,
    CASE_NUMBER TEXT NOT NULL,
    EVENT_NUMBER INTEGER NOT NULL,
    DATE TEXT NOT NULL,
    TIME TEXT,
    OFFICER TEXT,
    RESULT TEXT,
    TYPE TEXT NOT NULL,
    FOREIGN KEY(CASE_NUMBER) REFERENCES CASE_DETAIL(CASE_NUMBER),
    UNIQUE(CASE_NUMBER, EVENT_NUMBER)
)
