CREATE TABLE DISPOSITION (
    ID SERIAL PRIMARY KEY,
    CASE_NUMBER TEXT NOT NULL UNIQUE,
    TYPE TEXT,
    DATE TEXT NOT NULL,
    AMOUNT TEXT,
    AWARDED_TO TEXT,
    AWARDED_AGAINST TEXT,
    FOREIGN KEY(CASE_NUMBER) REFERENCES CASE_DETAIL(CASE_NUMBER)
);
